version: "3"
services:
  test_database:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: md_homework
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: '%'
      command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./ddl/:/docker-entrypoint-initdb.d/          
      ports:
        - 8306:3306   

  test_application:
      build: .
      ports:
        - 8080:8080
      depends_on:
        - test_database